title:              Welcome to My Data Playground
email:              thaole@gmail.com
description:        A Blog About Data analytics | RPA | Machine Learning
author:             Thao Le
baseurl:            "/DataPlayground"
url:                "https://thaole73.github.io"

# Social Profiles
twitter_username:   
github_username:   thaole73
# facebook_username:  
instagram_username:  
linkedin_username: 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  # - jekyll-paginate-v2
collections:
  portfolio:
    output: true

defaults:
   - scope:
       path: ""
       type: "posts"
     values:
       layout: "default"
       category: "Data Analytics"


#theme: jekyll-theme-clean-blog
# pagination:
#   enabled: true
#   collections:
#     blog:
#       per_page: 5
#       permalink: /portfolio/page:num/
#     posts:
#       per_page: 5
#       permalink: /posts/page:num/